---
title: "MM_2019_W01"
author: "Pratik C"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, 
                      fig.width = 12, fig.height = 12,
                      echo = TRUE, eval = TRUE)
options(warn = 1)
```

## Set environment
```{r}
# Load libraries
library(tidyverse)
library(hrbrthemes)
library(ggpmisc)
library(ggtext)
library(ggalt)
library(ggforce)
library(ggrepel)
library(ggfittext)
library(patchwork)
library(rvest)
library(lubridate)
library(sf)
library(osmdata)
library(mapview)
library(sfnetworks)
library(tidygraph)

# Load themes script
source(file = "C:\\Stuff\\Datasets\\vaw_themes.R")

# Set working directory
setwd("C:\\Stuff\\Datasets\\isochron-indianrailways/")
```

## Functions
```{r}

```

## Load data
```{r}
# Create BB for Kolkata
ymax <- 23.0102
ymin <- 22.3056
xmin <- 88.0513
xmax <- 88.5498
# Create bounding box
bbox <- c(xmin = xmin, ymin = ymin,
          xmax = xmax, ymax = ymax)

# Get railway stations
feat_railway_stations <- opq(bbox = bbox, timeout = 100) %>% 
  add_osm_feature(key = "railway",
                  value = c("station", "stop", "halt")) %>%
  osmdata_sf() %>%
  # Extract data
  `$`("osm_points")

# Get main roads
# feat_major_road <- opq(bbox = bbox, timeout = 100) %>% 
#   add_osm_feature(key = "highway",
#                   value = c("motorway", "motorway_link", 
#                             "trunk", "trunk_link", 
#                             "primary", "primary_link",
#                             "secondary", "secondary_link",
#                             "tertiary", "tertiary_link",
#                             "unclassified", "residential")) %>% 
#   osmdata_sf()
# # Save
# write_rds(x = feat_major_road, file = "kolkata_roads.rds")
feat_major_road <- read_rds(file = "kolkata_roads.rds")
```

## Process data
```{r}
# Find nearest points on road network to each station ---------------------
# data_road_near_station <- shp_railway_station %>% 
#   st_distance(y = feat_major_road$osm_lines %>% 
#                 select(osm_id)) %>% 
#   # Min distance of each point from nearest road
#   apply(MARGIN = 1, FUN = function(x){which(x == min(x))}) %>% 
#   # Convert to matrix
#   sapply(c) %>% 
#   # Convert to tibble
#   as_tibble_col() %>% 
#   # Extract elements
#   mutate(index_road = map_int(.x = value, .f = ~.x[1])) %>% 
#   # Rename list columns
#   select(index_road) %>% 
#   # Add index of station
#   mutate(index_station = row_number()) %>% 
#   # Get station name
#   left_join(y = shp_railway_station %>% 
#               # Set index
#               mutate(index_station = row_number()) %>% 
#               # Keep required columsn
#               select(index_station, name),
#             by = "index_station") %>% 
#   # Get geometry of road
#   left_join(y = feat_major_road$osm_lines %>% 
#               select(osm_id) %>% 
#               # Add index column
#               mutate(index_road = row_number()),
#             by = "index_road",
#             suffix = c("_station", "_road")) %>% 
#   # Calculate location on road nearest to station 
#   mutate(geometry_point = map2(.x = geometry_station, .y = geometry_road, 
#                                .f = ~st_nearest_points(x = .x, y = .y) %>% 
#                                  # Convert to point geom
#                                  st_cast(to = "POINT") %>% 
#                                  # Extract 2nd point, as first is original station location
#                                  `[` (2) %>% 
#                                  # Get coordinates
#                                  st_coordinates())) %>% 
#   # remove other geometry columns
#   select(index_station, name, geometry_point) %>% 
#   # Unlist column
#   unnest_wider(col = geometry_point, names_repair = "minimal") %>% 
#   # Rename
#   rename(lon = `...1`, lat = `...2`) %>% 
#   # Convert to sf
#   st_as_sf(coords = c("lat", "lon"), agr = "identity", 
#            crs = st_crs(shp_railway_station))
  
# Create SF network object from road geometries -----------------------
# First, round off coords to 4th decimal, to increase connectivity
shp_major_road <- feat_major_road$osm_lines %>% 
  # Remove extra columns
  select(osm_id, name, alt_name, highway) %>% 
  # Round precision to 3 decimals
  st_set_geometry(value = st_geometry(.) %>% 
                    lapply(FUN = function(x) round(x, 3)) %>% 
                    st_sfc(crs = st_crs(x = feat_major_road$osm_lines)))

# Convert to network ------------------------------
sfnet_road <- as_sfnetwork(x = shp_major_road, directed = FALSE) %>% 
  # Remove multiple edges
  activate(what = "edges") %>% 
  # arrange by legth
  arrange(edge_length()) %>% 
  # Remove loops and MEs
  filter(!edge_is_multiple()) %>% 
  filter(!edge_is_loop()) %>% 
  # Smooth network
  convert(.f = to_spatial_smooth) %>% 
  # Subdivude edges
  convert(.f = to_spatial_subdivision)

# To simplify, first find clusters
node_clusters <- dbscan::dbscan(x = sfnet_road %>% 
                                  # Extract node coordinates
                                  activate(what = "nodes") %>% 
                                  st_coordinates(),
                                # Set distance to 0.0001
                                eps = 0.001, minPts = 1)$cluster
# Add cluster info to network
sfnet_road <- sfnet_road %>% 
  activate(what = "nodes") %>% 
  mutate(cluster = node_clusters) %>% 
  # Contract
  convert(.f = to_spatial_contracted, cluster, simplify = TRUE) %>% 
  # Extract first component
  filter(group_components() == 1)

# Find points on road network nearest to railways stations -----------------
shp_railway_station <- feat_railway_stations %>% 
  # Remove ones with no name and duplicates
  filter(!is.na(name)) %>% 
  # Keep columns
  select(name) %>% 
  distinct(name, .keep_all = TRUE) %>% 
  # Drop specific duplicates
  filter(!name %in% c("Ballygunge Junction", "Barra Bazar",
                      "Seoraphuli Junction")) %>% 
  # Round off to 3 decimals
  st_set_geometry(value = st_geometry(.) %>% 
                    lapply(FUN = function(x) round(x, 3)) %>% 
                    st_sfc(crs = st_crs(x = shp_major_road))) %>% 
  # Add column to mark as railway
  mutate(type = "station")

# Create blended network --------------------------------
sfnet_road_blend <- st_network_blend(x = sfnet_road, 
                                     y = shp_railway_station, 
                                     tolerance = 750)

# Extract the new railway nodes formed as result of blending -----------------
shp_railway_nodes <- sfnet_road_blend %>% 
  activate("nodes") %>% 
  filter(!is.na(name)) %>% 
  st_as_sf() %>% 
  select(-`.tidygraph_node_index`, -type)

# Create geometry of all points in plane -------------------------
# First latitude, since its constant
diff_y <- 0.05/111.321
# Y distance will depend on coordinate
diff_x <- 0.05/(111.321 * cos(abs(mean(c(ymax, ymin))) * pi/180))

shp_plane <- tibble(x = seq(from = xmin, to = xmax, by = diff_x),
                     y = list(seq(from = ymin, to = ymax, by = diff_y))) %>% 
  # Long form
  unnest_longer(col = y) %>% 
  # Add index
  mutate(index = row_number()) %>% 
  # Convert to sf
  st_as_sf(coords = c("x", "y"), crs = st_crs(shp_major_road), 
           agr = "identity", remove = FALSE) %>% 
  # Add column to mark as plane points
  mutate(type = "plane") %>% 
  # Remove extra columns
  select(index, type)

# Get nearest node in network to each point
shp_plane_near_node <- shp_plane %>% 
  mutate(near_node = st_nearest_feature(x = ., y = sfnet_road_blend))

# Extract unique network nodes
shp_plane_network_node <- sfnet_road_blend %>% 
  # Filter nodes that map to plane points
  activate(what = "nodes") %>% 
  # Conver to sf
  st_as_sf() %>% 
  # Set node index
  mutate(node_index = row_number()) %>% 
  # Unlist the index column
  filter(node_index %in% unique(shp_plane_near_node$near_node))

# Add column to store distance of plane point from nearest node
shp_plane_near_node$extra_dist <- shp_plane_near_node %>% 
  # Sort
  arrange(index) %>% 
  # Calculate
  st_distance(y = shp_plane_network_node %>% 
                select(node_index) %>% 
                # Map corresponding points on plane
                right_join(y = shp_plane_near_node %>% 
                             as_tibble() %>% 
                             select(index, near_node),
                           by = c("node_index" = "near_node")) %>% 
                # Arranmge in order of index
                arrange(index),
              by_element = TRUE) %>% 
  as.integer()

# Calculate Origin Destination matrix -------------------------------
t0 <- Sys.time()
data_dist <- st_network_cost(x = sfnet_road_blend, 
                             to = shp_railway_nodes, 
                             from = shp_plane_network_node) %>% 
  # Calculate row minimums
  matrixStats::rowMins() %>% 
  # Convert to tibble
  as_tibble() %>% 
  rename(dist = value) %>% 
  # Column for index
  mutate(near_node = shp_plane_network_node$node_index[row_number()]) %>% 
  # Get all plane nodes mapped to network mode
  left_join(y = shp_plane_near_node,
            by = "near_node") %>% 
  # Extract coordinates
  mutate(coords = map(.x = geometry, .f = function(x){
    st_coordinates(x) %>% 
    as.numeric() %>% 
    set_names(nm = c("x", "y"))}),
    # Total dist
    total_dist = dist + extra_dist) %>% 
  unnest_wider(col = coords) %>% 
  # Keep columns
  select(x, y, dist, total_dist)
difftime(time1 = Sys.time(), time2 = t0)

```

## Visualize
```{r}
# Set scale fill type
fill_scale <- "Quantile"
# Set breaks for scale
legend_breaks <- case_when(
    fill_scale == "Linear" ~ seq.int(from = min(data_dist$total_dist),
                                     to = max(data_dist$total_dist),
                                     length.out = 13) %>% as.integer(),
    fill_scale == "Quantile" ~ quantile(x = data_dist$dist, 
                                        c(seq(from = 0, 
                                            to = 0.9, 
                                            by = 0.1), 
                                          c(0.96, 0.99, 1))) %>% as.integer())
# Plot raster
plot_map <- ggplot() + 
  geom_raster(data = data_dist,
              mapping = aes(x = x, y = y, fill = total_dist)) +
  # Scales
  scale_x_continuous(name = NULL,
                       breaks = NULL,
                       expand = expansion(mult = c(0.05, 0.05))) +
  scale_y_continuous(name = NULL,
                       breaks = NULL,
                       expand = expansion(mult = c(0.05, 0.05))) +
  binned_scale(aesthetics = "fill", 
               scale_name = "stepsn", 
               palette = function(x) viridisLite::viridis(n = length(legend_breaks) - 1, 
                                                          begin = 1, 
                                                          end = 0),
               breaks = legend_breaks,
               limits = range(data_dist$dist),
               show.limits = TRUE) +
  # Frame limits
  coord_sf(xlim = c(xmin, xmax),
           ylim = c(ymin, ymax),
           expand = expansion(mult = c(0.0, 0.0))) +
  guides(fill = guide_legend(override.aes = list(colour = "black"))) +
  labs(title = "How Far to the Nearest Station?", 
  subtitle = "Distance of places in Calcutta to the nearest railway station", 
  caption = "Data: OpenStreetMap Contribtors\nDesign: @JediPro") +
  theme_vaw_light() +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = NA, colour = "black", size = 0.5),
        strip.text = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.key.width = unit(9, "mm"),
        # legend.position = c(0.87, 0.13),
        # legend.direction = "horizontal"
        )

# Save
t0 <- Sys.time()
ggsave(filename = "calcutta_isodistance_railway_station.png", 
       plot = plot_map, device = "png", 
       width = 25, height = 40, units = "cm", dpi = 300, limitsize = FALSE)
print(Sys.time() - t0)
```

